owner: camphor-
repo: status
user-agent: camphor-/status
sites:
  - name: Website
    url: https://camph.net
  - name: Books
    url: https://books.camph.net
  - name: Account
    url: https://account.camph.net
  - name: Advent
    url: https://advent.camph.net
  - name: API
    url: https://api.camph.net
  - name: Blog
    url: https://blog.camph.net
  - name: TechBlog
    url: https://tech.camph.net
  - name: Calendar
    url: https://cal.camph.net
  - name: Feeds
    url: https://feeds.camph.net
  - name: House
    url: https://house.camph.net
  - name: ISPJ
    url: https://ipsj.camph.net
  - name: Jinrou
    url: https://jinrou.camph.net    
  - name: Python Tutorial
    url: https://python-tutorial.camph.net
  - name: Registry
    url: https://registry.camph.net
  - name: Relaym API Prod
    url: https://relaym-api.camph.net
notifications:
  - type: slack
    channel: C016QTU9S9Y
assignees:
  - AnandChowdhary
status-website:
  cname: status.camph.net
  logoUrl: https://raw.githubusercontent.com/koj-co/upptime/79d9d1c22ecf706acc51f17798d7c7dbc710ab40/assets/icon.svg
  name: CAMPHOR- Status
  introTitle: "**CAMPHOR- Status** はCAMPHOR-が運営しているサービスの状態をチェックしています。"
  introMessage: This is a sample status page which uses **real-time** data from our [Github repository](https://github.com/koj-co/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/koj-co/upptime)
