owner: camphor-
repo: status
user-agent: camphor-/status
sites:
  - name: Website
    url: https://camph.net
  - name: Books
    url: https://books.camph.net
  - name: Account
    url: https://account.camph.net
  - name: Advent
    url: https://advent.camph.net
  - name: Blog
    url: https://blog.camph.net
  - name: TechBlog
    url: https://tech.camph.net
  - name: Calendar
    url: https://cal.camph.net
  - name: Feeds
    url: https://feeds.camph.net/public/feeds.json
  - name: House
    url: https://house.camph.net
  - name: IPSJ
    url: http://ipsj.camph.net/
  - name: Jinrou
    url: http://jinrou.camph.net    
  - name: Python Tutorial
    url: http://python-tutorial.camph.net
  - name: Relaym API Prod
    url: https://relaym-api.camph.net/api/v3/sessions/06b7db29-b1d7-4ae7-bfdf-ddaf0f4274c3
  - name: Registry (Internal)
    url: $SECRET_SITE
assignees:
  - camphor-/root
status-website:
  cname: status.camph.net
  logoUrl: https://raw.githubusercontent.com/camphor-/status/master/camphor_logo.svg
  name: CAMPHOR- Status
  introTitle: "**CAMPHOR- Status** ではCAMPHOR-が運営しているサービスの状態をチェックしています。"
  introMessage: 
